[package]
name = "chip8-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
log = "0.4"
tui = "0.19"
tui-logger = "0.8"
crossterm = "0.25"
device_query = "1.1"
spin_sleep = "1.1.1"